source 'https://rubygems.org'

gem 'jekyll', '~> 4.2.0'
gem 'kramdown-parser-gfm', '~> 1.1.0'
gem 'ffi', '~> 1.15'
gem 'faraday-retry'
gem 'jekyll-seo-tag'
gem 'jekyll-paginate'
gem 'jekyll-sitemap'
gem 'jekyll-feed'