name: Build and Deploy
on:
  push:
    branches:
      - main  # 指定触发工作流的分支
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # 运行环境
    steps:
    - uses: actions/checkout@v2  # 检出代码

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # 确保使用的是 Node.js 16 版本

    - name: Install dependencies
      run: |
        export NODE_OPTIONS=--openssl-legacy-provider
        npm install  # 安装依赖

    - name: Build
      run: |
        export NODE_OPTIONS=--openssl-legacy-provider
        npm run build  # 构建项目

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # 使用GitHub为每个仓库自动生成的令牌
        publish_dir: ./build  # 指定构建产物的目录